name: design_patterns
description: Adapt patterns from the book "Design Patterns" by Eric Freeman, Elizabeth Robson into Dart language.
version: 1.0.0

environment:
  sdk: '>=2.15.1 <3.0.0'

dev_dependencies:
  dart_code_metrics: ^4.14.0
  flutter_lints: ^1.0.4
  lints: ^1.0.1
  